# Generated by Django 5.1.7 on 2025-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
