# Generated by Django 5.1.7 on 2025-03-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cake_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=30, null=True)),
                ('cimg', models.FileField(blank=True, null=True, upload_to='pic')),
                ('cprice', models.IntegerField()),
            ],
        ),
    ]
