# Generated by Django 5.1.7 on 2025-03-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_cake_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake_reg')),
            ],
        ),
    ]
